# Generated by Django 5.2 on 2025-04-29 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delegate_category', models.CharField(choices=[('category1', 'Category 1'), ('category2', 'Category 2'), ('category3', 'Category 3')], max_length=50)),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('nationality', models.CharField(max_length=30)),
                ('national_id', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('organization', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('country_of_residence', models.CharField(max_length=30)),
                ('social_activities', models.CharField(choices=[('activity1', 'Activity 1'), ('activity2', 'Activity 2'), ('activity3', 'Activity 3')], max_length=50)),
            ],
        ),
    ]
